from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]

DATA_DIR = PROJECT_ROOT / "data"
DATA_INPUT_DIR = DATA_DIR / "input"
DATA_OUTPUT_DIR = DATA_DIR / "output"
TREES_OUTPUT_DIR = DATA_OUTPUT_DIR / "trees"
ORTHOLOGS_OUTPUT_DIR = DATA_OUTPUT_DIR / "orthologs"
MSA_OUTPUT_DIR = DATA_OUTPUT_DIR / "msa"
CONSERVATION_OUTPUT_DIR = DATA_OUTPUT_DIR / "conservation"
VARIANTS_OUTPUT_DIR = DATA_OUTPUT_DIR / "variants"
